Fix missing target library (mvfst_client_client) for samples/echo (#465)
Summary:
Building the samples resulted in a linker error:

undefined reference to `quic::QuicClientTransportLite::...` undefined reference to `vtable for quic::QuicClientTransport' undefined reference to `VTT for quic::QuicClientTransport'

This may have been introduced in 5cd8b2b, with the addition of QuicClientTransportLite.

## Testing

./getdeps.sh --extra-cmake-defines '{"BUILD_SAMPLES":"ON"}'

This should produce:

...build/mvfst/quic/samples/echo

Pull Request resolved: https://github.com/facebook/mvfst/pull/465

Reviewed By: JunqiWang

Differential Revision: D114390994

Pulled By: jbeshay

fbshipit-source-id: 1d3361a054e45979b54259b74a88b6937afccc7a