change [[nodiscard]] to FOLLY_NODISCARD
Summary:
ovrsource is not happy about [[nodiscard]] when sync: https://www.internalfb.com/intern/sandcastle/job/18014398812129193/
```c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-win\buck-out\gen\xplat\quic\fb-quicwindows#header-mode-symlink-tree-only,headers\quic\api\quictransportbase.h(373): error C2429: attribute 'nodiscard' requires compiler flag '/std:c++17'```

Reviewed By: bschlinker

Differential Revision: D22700852

fbshipit-source-id: 4821ad9f81f95a11123c7d475144c5e054d6d34e