Fix missing target library (mvfst_client_client) for samples/echo
Building the samples resulted in a linker error:

undefined reference to `quic::QuicClientTransportLite::...`
undefined reference to `vtable for quic::QuicClientTransport'
undefined reference to `VTT for quic::QuicClientTransport'

This may have been introduced in 5cd8b2b, with the addition of
QuicClientTransportLite.

Test:

./getdeps.sh --extra-cmake-defines '{"BUILD_SAMPLES":"ON"}'

This should produce:

...build/mvfst/quic/samples/echo