Fix dependencies
Summary:
Add a few missing dependencies uncovered by D74904617.

Fixes:

```
xplat/quic/common/test/QuicBufferTest.cpp:8:10: fatal error: 'glog/logging.h' file not found
    8 | #include <glog/logging.h>
      |          ^~~~~~~~~~~~~~~~

xplat/papaya/client/work/test/FunctionalTest.cc:5:10: fatal error: 'folly/String.h' file not found
    5 | #include <folly/String.h>
      |          ^~~~~~~~~~~~~~~~

xplat/papaya/fb/store/manager/test/ManagerTest.cc:5:10: fatal error: 'folly/Singleton.h' file not found
    5 | #include <folly/Singleton.h>
      |          ^~~~~~~~~~~~~~~~~~~

xplat/mcfcpp/McfUtils/test/execution.cpp:6:10: fatal error: 'folly/Function.h' file not found
    6 | #include <folly/Function.h>
      |          ^~~~~~~~~~~~~~~~~~

xplat/thrift/compiler/test/source_location_test.cc:23:10: fatal error: 'folly/ScopeGuard.h' file not found
   23 | #include <folly/ScopeGuard.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```

Reviewed By: yoney, hanidamlaj

Differential Revision: D75077432

fbshipit-source-id: 16334a846950a834f8ee165c22101428506070b5